TRAINING_DATA = [
    "Ekáàro",
    "Ẹkú ojúmọ́",
    "Gbogbo ilé ńkọ́?",
    "Alaafia lawà",
    "Mo mà ri yín lòní, sé kò sí?",
    "Kó má bà sí ni",
    "Kí ló sẹ lẹ̀?",
    "Èmi àti àbúrò mi jà lana",
    "Ẹ̀yin àti àbúrò yín jà lana?",
    "Bẹ́ẹ̀ ni",
    "Àbúrò yín wo?",
    "Adé ọmọ ìyá mi",
    "Adé ọmọ ìyá yin?",
    "Bẹ́ẹ̀ ni",
    "Kí ló sẹ lẹ̀?",
    "Kò fẹ́ dá owó ní pàdé mòlẹ́bí ni",
    "Ẹ sàlàyé síwájú si",
    "Owó àwọn obìrin ilé ni",
    "Kò yé mi tó",
    "Owó ìdàgbà sókè ni",
    "Ẹ sọ fun pé kó wá rí mi",
    "Ẹ seun",
    "Kò tópẹ́",
    "Ódàbọ̀"
]

FLOW = {
    "Ẹkú ojúmọ́": ["Gbogbo ilé ńkọ́?"],
    "Alaafia lawà": ["Mo mà ri yín lòní, sé kò sí?"],
    "Kó má bà sí ni": ["Kí ló sẹ lẹ̀?"],
    "Èmi àti àbúrò mi jà lana": ["Ẹ̀yin àti àbúrò yín jà lana?"],
    "Bẹ́ẹ̀ ni": ["Àbúrò yín wo?"],
    "{%name%} ọmọ ìyá mi": ["{%name%} ọmọ ìyá yin?"],
    "Bẹ́ẹ̀ ni": ["Kí ló sẹ lẹ̀?"],
    "Kò fẹ́ dá owó ní pàdé mòlẹ́bí ni": ["Ẹ sàlàyé síwájú si"],
    "Owó àwọn obìrin ilé ni": ["Kò yé mi tó"],
    "Owó ìdàgbà sókè ni": ["Ẹ sọ fun pé kó wá rí mi"],
    "Ẹ seun": ["Kò tópẹ́"],
    "Ódàbọ̀": ["Ódàbọ̀"],
    "{%greeting%}": ["{%greeting%}, gbogbo ilé ńkọ́?"],
    "{%name%}": ["kín ni {%name%} se?"]
}